Revert "Implement byte editing, default docstring, printing registers with offsets"
Traceback (most recent call last):
  File "~/tool/peda/peda.py", line 6065, in <module>
  File "~/tool/peda/peda.py", line 5971, in __init__
  File "~/tool/peda/peda.py", line 3088, in _get_helptext
AttributeError: attribute '__doc__' of 'instancemethod' objects is not writable

This reverts commit abf1e61ab69da17e9c17d5850a03c5ad6a2a6bec.

Conflicts:
	peda.py